/**
 * Blockly Toolbox Configuration
 * Auto-generated by Block Creator Tool
 */

function getCommonCategories() {
    return [
        {
            "kind": "category",
            "name": "🔧 Structure",
            "colour": "#3949AB",
            "contents": [
                {
                    "kind": "block",
                    "type": "base_setup_loop"
                }
            ]
        },
        {
            "kind": "category",
            "name": "⏱️ Timing",
            "colour": "#424242",
            "contents": [
                {
                    "kind": "block",
                    "type": "custom_wait"
                },
                {
                    "kind": "block",
                    "type": "custom_timer"
                },
                {
                    "kind": "block",
                    "type": "start_timekeeping"
                },
                {
                    "kind": "block",
                    "type": "get_duration"
                },
                {
                    "kind": "block",
                    "type": "state_duration"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🎛️ Arduino",
            "colour": "#5E35B1",
            "contents": [
                {
                    "kind": "block",
                    "type": "esp32_digital_write"
                },
                {
                    "kind": "block",
                    "type": "esp32_digital_state"
                },
                {
                    "kind": "block",
                    "type": "esp32_analog_write"
                },
                {
                    "kind": "block",
                    "type": "esp32_analog_read"
                },
                {
                    "kind": "block",
                    "type": "esp32_toggle_pin"
                },
                {
                    "kind": "block",
                    "type": "esp32_interrupt"
                },
                {
                    "kind": "block",
                    "type": "esp32_detach_interrupt"
                },
                {
                    "kind": "block",
                    "type": "esp32_restart"
                },
                {
                    "kind": "block",
                    "type": "esp32_deep_sleep"
                }
            ]
        },
        {
            "kind": "category",
            "name": "abc Text",
            "colour": "#388E3C",
            "contents": [
                {
                    "kind": "block",
                    "type": "custom_text_value",
                    "fields": {
                        "TEXT": ""
                    }
                },
                {
                    "kind": "block",
                    "type": "custom_text_value",
                    "fields": {
                        "TEXT": ""
                    }
                },
                {
                    "kind": "block",
                    "type": "casting_to_char"
                },
                {
                    "kind": "block",
                    "type": "convert_to_string"
                },
                {
                    "kind": "block",
                    "type": "convert_to_string_decimal",
                    "fields": {
                        "DECIMALS": "5"
                    }
                },
                {
                    "kind": "block",
                    "type": "text_join"
                },
                {
                    "kind": "block",
                    "type": "text_length"
                },
                {
                    "kind": "block",
                    "type": "text_isEmpty"
                },
                {
                    "kind": "block",
                    "type": "text_append"
                },
                {
                    "kind": "block",
                    "type": "text_indexOf"
                },
                {
                    "kind": "block",
                    "type": "text_charAt"
                },
                {
                    "kind": "block",
                    "type": "text_getSubstring"
                },
                {
                    "kind": "block",
                    "type": "text_changeCase"
                },
                {
                    "kind": "block",
                    "type": "text_trim"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔄 Control",
            "colour": "#FFAB19",
            "contents": [
                {
                    "kind": "block",
                    "type": "controls_if"
                },
                {
                    "kind": "block",
                    "type": "ifelse"
                },
                {
                    "kind": "block",
                    "type": "ifandifnot"
                },
                {
                    "kind": "block",
                    "type": "controls_repeat_ext"
                },
                {
                    "kind": "block",
                    "type": "controls_whileUntil"
                },
                {
                    "kind": "block",
                    "type": "controls_for"
                },
                {
                    "kind": "block",
                    "type": "controls_forEach"
                },
                {
                    "kind": "block",
                    "type": "controls_switch"
                },
                {
                    "kind": "block",
                    "type": "controls_flow_statements"
                },
                {
                    "kind": "block",
                    "type": "logic_operation"
                },
                {
                    "kind": "block",
                    "type": "logic_negate"
                },
                {
                    "kind": "block",
                    "type": "logic_null"
                },
                {
                    "kind": "block",
                    "type": "inout_onoff"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔢 Operators",
            "colour": "#388E3C",
            "contents": [
                {
                    "kind": "block",
                    "type": "math_number"
                },
                {
                    "kind": "block",
                    "type": "logic_boolean"
                },
                {
                    "kind": "block",
                    "type": "math_arithmetic"
                },
                {
                    "kind": "block",
                    "type": "logic_compare"
                },
                {
                    "kind": "block",
                    "type": "math_single"
                },
                {
                    "kind": "block",
                    "type": "math_trig"
                },
                {
                    "kind": "block",
                    "type": "math_constant"
                },
                {
                    "kind": "block",
                    "type": "math_modulo"
                },
                {
                    "kind": "block",
                    "type": "math_round"
                },
                {
                    "kind": "block",
                    "type": "math_random_int"
                },
                {
                    "kind": "block",
                    "type": "math_number_property"
                },
                {
                    "kind": "block",
                    "type": "intervalle"
                },
                {
                    "kind": "block",
                    "type": "custom_text_value",
                    "fields": {
                        "TEXT": "hello"
                    }
                },
                {
                    "kind": "block",
                    "type": "text_join"
                },
                {
                    "kind": "block",
                    "type": "text_length"
                },
                {
                    "kind": "block",
                    "type": "text_isEmpty"
                },
                {
                    "kind": "block",
                    "type": "custom_math_map"
                },
                {
                    "kind": "block",
                    "type": "custom_math_random_int"
                },
                {
                    "kind": "block",
                    "type": "custom_math_constrain"
                },
                {
                    "kind": "block",
                    "type": "cast_to_byte"
                },
                {
                    "kind": "block",
                    "type": "cast_to_unsigned_int"
                },
                {
                    "kind": "block",
                    "type": "cast_to_int"
                },
                {
                    "kind": "block",
                    "type": "cast_to_float"
                }
            ]
        },
        {
            "kind": "category",
            "name": "✖️ Variables",
            "colour": "#D32F2F",
            "custom": "VARIABLE_DYNAMIC"
        },
        {
            "kind": "category",
            "name": "🔔 Communicate",
            "colour": "#1976D2",
            "contents": [
                {
                    "kind": "category",
                    "name": "i USB Serial",
                    "colour": "#0277BD",
                    "contents": [
                        {
                            "kind": "block",
                            "type": "usb_serial_init"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_available"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_read_byte"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_read_string_until"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_read_number_until"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_print_format"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_print_same_line"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_print_new_line"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_write"
                        },
                        {
                            "kind": "block",
                            "type": "custom_text_value",
                            "fields": {
                                "TEXT": "message"
                            }
                        }
                    ]
                },
                {
                    "kind": "category",
                    "name": "Bluetooth",
                    "colour": "#01579B",
                    "contents": [
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_init"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_available"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_read_byte"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_read_string_until"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_read_number_until"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_print_format"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_print_same_line"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_print_new_line"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_write"
                        },
                        {
                            "kind": "block",
                            "type": "custom_text_value",
                            "fields": {
                                "TEXT": "message"
                            }
                        }
                    ]
                }
            ]
        }
    ];
}

function getEmmiBipedalCategories() {
    return [
        {
            "kind": "category",
            "name": "📡 IR",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "ir_detect_white"
                },
                {
                    "kind": "block",
                    "type": "ir_detect_black"
                }
            ]
        },
        {
            "kind": "category",
            "name": "⚙️ Wheels",
            "colour": "#4759F5",
            "contents": [
                {
                    "kind": "block",
                    "type": "flipper_wheels_init"
                },
                {
                    "kind": "block",
                    "type": "flipper_wheels_move"
                }
            ]
        },
        {
            "kind": "category",
            "name": "👓 Ultrasonic",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "flipper_ultrasonic_init",
                    "fields": {
                        "US_NUMBER": "1",
                        "PIN_TRIG": "25",
                        "PIN_ECHO": "33"
                    }
                },
                {
                    "kind": "block",
                    "type": "flipper_ultrasonic_distance",
                    "fields": {
                        "US_NUMBER": "1"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🚥 RGB",
            "colour": "#00838F",
            "contents": [
                {
                    "kind": "block",
                    "type": "flipper_rgb_red"
                },
                {
                    "kind": "block",
                    "type": "flipper_rgb_green"
                },
                {
                    "kind": "block",
                    "type": "flipper_rgb_blue"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🖥️ OLED Eyes",
            "colour": "#B655F5",
            "contents": [
                {
                    "kind": "block",
                    "type": "flipper_oled_init"
                },
                {
                    "kind": "block",
                    "type": "OLED_eyes"
                },
                {
                    "kind": "block",
                    "type": "flipper_oled_clear"
                }
            ]
        },
        {
            "kind": "category",
            "name": "👉 Touch",
            "colour": "#FFC107",
            "contents": [
                {
                    "kind": "block",
                    "type": "flipper_touch_read"
                }
            ]
        },
        {
            "kind": "category",
            "name": "💡 Light",
            "colour": "#FFA726",
            "contents": [
                {
                    "kind": "block",
                    "type": "flipper_light_read"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔊 Speaker",
            "colour": "#FF63BB",
            "contents": [
                {
                    "kind": "block",
                    "type": "flipper_speaker_init"
                },
                {
                    "kind": "block",
                    "type": "flipper_speaker_play"
                },
                {
                    "kind": "block",
                    "type": "flipper_speaker_stop"
                },
                {
                    "kind": "block",
                    "type": "flipper_buzzer_rtttl",
                    "fields": {
                        "PIN": "26"
                    }
                },
                {
                    "kind": "block",
                    "type": "flipper_buzzer_note",
                    "fields": {
                        "PIN": "26"
                    }
                },
                {
                    "kind": "block",
                    "type": "flipper_buzzer_tone",
                    "fields": {
                        "PIN": "26"
                    }
                },
                {
                    "kind": "block",
                    "type": "flipper_buzzer_stop",
                    "fields": {
                        "PIN": "26"
                    }
                }
            ]
        }
    ];
}

function getEmmiBotV2Categories() {
    return [
        {
            "kind": "category",
            "name": "👀 Eyes",
            "colour": "#CB4335",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_eyes_digital"
                }
            ]
        },
        {
            "kind": "category",
            "name": "💪 Wheels",
            "colour": "#5D4037",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_wheels_simple"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔊 Buzzer",
            "colour": "#E91E63",
            "contents": [
                {
                    "kind": "block",
                    "type": "buzzer_play_rtttl"
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_rtttl_custom"
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_note"
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_tone"
                },
                {
                    "kind": "block",
                    "type": "buzzer_stop"
                }
            ]
        },
        {
            "kind": "category",
            "name": "👉 Touch",
            "colour": "#FFC107",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_touch_read"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔦 Mic",
            "colour": "#1A237E",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_mic_read"
                }
            ]
        },
        {
            "kind": "category",
            "name": "💡 Light",
            "colour": "#FFA726",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_light_read"
                }
            ]
        }
    ];
}

function getEmmiV1Categories() {
    return [
        {
            "kind": "category",
            "name": "💡 Light",
            "colour": "#FFA726",
            "contents": [
                {
                    "kind": "block",
                    "type": "bipedal_light_read"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🖥️ OLED Eyes",
            "colour": "#B655F5",
            "contents": [
                {
                    "kind": "block",
                    "type": "OLED_cust"
                },
                {
                    "kind": "block",
                    "type": "OLED_eyes"
                },
                {
                    "kind": "block",
                    "type": "OLED_clear"
                }
            ]
        },
        {
            "kind": "category",
            "name": "👓 Ultrasonic",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "ultrasonic_sensor",
                    "fields": {
                        "US_NUMBER": "1",
                        "PIN_TRIG": "25",
                        "PIN_ECHO": "33"
                    }
                },
                {
                    "kind": "block",
                    "type": "ultrasonic_distance",
                    "fields": {
                        "US_NUMBER": "1"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🚥 RGB",
            "colour": "#00838F",
            "contents": [
                {
                    "kind": "block",
                    "type": "bipedal_rgb_green"
                },
                {
                    "kind": "block",
                    "type": "bipedal_rgb_red"
                },
                {
                    "kind": "block",
                    "type": "bipedal_rgb_blue"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔊 Speaker",
            "colour": "#FF63BB",
            "contents": [
                {
                    "kind": "block",
                    "type": "speaker_init"
                },
                {
                    "kind": "block",
                    "type": "VOICE_play"
                },
                {
                    "kind": "block",
                    "type": "VOICE_stop"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔊 Buzzer",
            "colour": "#E91E63",
            "contents": [
                {
                    "kind": "block",
                    "type": "buzzer_play_rtttl",
                    "fields": {
                        "PIN": "26"
                    }
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_rtttl_custom",
                    "fields": {
                        "PIN": "26"
                    }
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_note",
                    "fields": {
                        "PIN": "26"
                    }
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_tone",
                    "fields": {
                        "PIN": "26"
                    }
                },
                {
                    "kind": "block",
                    "type": "buzzer_stop",
                    "fields": {
                        "PIN": "26"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🦵 Legs",
            "colour": "#4759F5",
            "contents": [
                {
                    "kind": "block",
                    "type": "bipedal_setup"
                },
                {
                    "kind": "block",
                    "type": "bipedal_home"
                },
                {
                    "kind": "block",
                    "type": "bipedal_move",
                    "fields": {
                        "otto_move_sens": "FORWARD",
                        "otto_move_speed": "1000"
                    }
                },
                {
                    "kind": "block",
                    "type": "bipedal_dance",
                    "fields": {
                        "otto_dance_movement": "moonwalkerLEFT",
                        "otto_move_speed": "1000",
                        "otto_dance_size": "15"
                    }
                },
                {
                    "kind": "block",
                    "type": "bipedal_do",
                    "fields": {
                        "otto_do_movement": "swing",
                        "otto_move_speed": "1000",
                        "otto_dance_size": "15"
                    }
                },
                {
                    "kind": "block",
                    "type": "bipedal_smooth"
                },
                {
                    "kind": "block",
                    "type": "bipedal_gesture",
                    "fields": {
                        "otto_gesture": "1"
                    }
                }
            ]
        }
    ];
}

function getExplorerKitCategories() {
    return [
        {
            "kind": "category",
            "name": "⭕ Tapmodule",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_tapmodule"
                }
            ]
        },
        {
            "kind": "category",
            "name": "📐 Tilt",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_tilt"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🧲 Magnetic",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_magnetic_reed"
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_magnetic_hall"
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_magnetic_hall_analog"
                }
            ]
        },
        {
            "kind": "category",
            "name": "↔️ Switch",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_switch_button"
                }
            ]
        },
        {
            "kind": "category",
            "name": "💥 Laser",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_digital_write",
                    "fields": {
                        "PIN": "14",
                        "STATE": "LOW"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "💡 LEDs",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_digital_write",
                    "fields": {
                        "PIN": "21",
                        "STATE": "LOW"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_digital_write",
                    "fields": {
                        "PIN": "19",
                        "STATE": "LOW"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_digital_write",
                    "fields": {
                        "PIN": "23",
                        "STATE": "LOW"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "💡 Light",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_analog_read",
                    "fields": {
                        "PIN": "34"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🎼 Buzzer",
            "colour": "#FF63BB",
            "contents": []
        },
        {
            "kind": "category",
            "name": "🎤 Mic",
            "colour": "#54BCF7",
            "contents": []
        },
        {
            "kind": "category",
            "name": "🟠 Shock",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_shock",
                    "fields": {
                        "PIN": "39",
                        "TRIGGER": "FALSE"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "😊 Infrared",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_ir_digital",
                    "fields": {
                        "PIN": "23"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_ir_sensed",
                    "fields": {
                        "PIN": "23"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_ir_analog",
                    "fields": {
                        "PIN": "33",
                        "OUTPUT": "raw"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_ir_write",
                    "fields": {
                        "PIN": "27",
                        "STATE": "LOW"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_flame_digital",
                    "fields": {
                        "PIN": "27"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_flame_analog",
                    "fields": {
                        "PIN": "39",
                        "OUTPUT": "raw"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔌 Relay",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_relay",
                    "fields": {
                        "STATE": "HIGH"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔲 Photo interrupter",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_photo_interrupter",
                    "fields": {
                        "PIN": "27"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "👆 Touch",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_touch_digital",
                    "fields": {
                        "PIN": "39",
                        "PRESSED": "FALSE"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_touch_analog",
                    "fields": {
                        "PIN": "27"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🌡 Temperature",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_temp_digital",
                    "fields": {
                        "PIN": "27"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_temp_analog",
                    "fields": {
                        "PIN": "27"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_temp_dht",
                    "fields": {
                        "NUM": "1",
                        "TYPE": "DHT11",
                        "MEASURE": "TEMP"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_temp_ntc",
                    "fields": {
                        "PIN": "33"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_temp_lm35",
                    "fields": {
                        "PIN": "33"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "💓 Heartbeat",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_heartbeat",
                    "fields": {
                        "PIN": "27"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🕹 Joystick",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_joystick_axis",
                    "fields": {
                        "AXIS": "X",
                        "PIN": "33",
                        "OUTPUT": "raw"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_joystick_button",
                    "fields": {
                        "PIN": "35"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "⚙️ Rotary encoder",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_encoder_init",
                    "fields": {
                        "NUM": "1",
                        "DT": "32",
                        "CLK": "35"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_encoder_write",
                    "fields": {
                        "NUM": "1",
                        "VALUE": "0"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_encoder_read",
                    "fields": {
                        "NUM": "1"
                    }
                },
                {
                    "kind": "block",
                    "type": "explorer_kit_encoder_button",
                    "fields": {
                        "NUM": "1",
                        "PIN": "33"
                    }
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔧 Other",
            "colour": "#54BCF7",
            "contents": [
                {
                    "kind": "block",
                    "type": "explorer_kit_mrtnode_button"
                }
            ]
        }
    ];
}

function getToolbox(boardType = 'emmi-bot-v2') {
    let categories = [];

    categories = categories.concat(getCommonCategories());

    switch (boardType) {
        case 'emmi-bipedal':
            categories = categories.concat(getEmmiBipedalCategories());
            break;
        case 'emmi-bot-v2':
            categories = categories.concat(getEmmiBotV2Categories());
            break;
        case 'emmi-v1':
            categories = categories.concat(getEmmiV1Categories());
            break;
        case 'explorer-kit':
            categories = categories.concat(getExplorerKitCategories());
            break;
    }

    return {
        kind: "categoryToolbox",
        contents: categories
    };
}

function getAvailableBoardTypes() {
    return [
        "emmi-bipedal",
        "emmi-bot-v2",
        "emmi-v1",
        "explorer-kit"
    ];
}

let ESP32Toolbox = getToolbox('emmi-bot-v2');

function getToolboxForBoard(boardType) {
    return getToolbox(boardType);
}

function getBoardFirmwareConfig() {
    return {
        "emmi-bot-v2": {
            "firmwareUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-v2/firmware.bin",
            "partitionsUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-v2/partitions.bin",
            "bootloaderUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-v2/bootloader.bin",
            "bootappUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-v2/boot_app0.bin",
            "versionUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-v2/version.txt"
        },
        "emmi-v1": {
            "firmwareUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-bipedal/firmware.bin",
            "partitionsUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-bipedal/partitions.bin",
            "bootloaderUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-bipedal/bootloader.bin",
            "bootappUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-bipedal/boot_app0.bin",
            "versionUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-bipedal/version.txt"
        },
        "emmi-bipedal": {
            "firmwareUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-flipper/firmware.bin",
            "partitionsUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-flipper/partitions.bin",
            "bootloaderUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-flipper/bootloader.bin",
            "bootappUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-flipper/boot_app0.bin",
            "versionUrl": "https://emmi-lite-firmware.s3.us-east-1.amazonaws.com/emmi-flipper/version.txt"
        }
    };
}