/**
 * Blockly Toolbox Configuration
 * Auto-generated by Block Creator Tool
 */

function getCommonCategories() {
    return [
        {
            "kind": "category",
            "name": "🔧 Structure",
            "colour": "#3949AB",
            "contents": [
                {
                    "kind": "block",
                    "type": "base_setup_loop"
                }
            ]
        },
        {
            "kind": "category",
            "name": "⏱️ Timing",
            "colour": "#424242",
            "contents": [
                {
                    "kind": "block",
                    "type": "custom_wait"
                },
                {
                    "kind": "block",
                    "type": "custom_timer"
                },
                {
                    "kind": "block",
                    "type": "start_timekeeping"
                },
                {
                    "kind": "block",
                    "type": "get_duration"
                },
                {
                    "kind": "block",
                    "type": "state_duration"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🎛️ Arduino",
            "colour": "#5E35B1",
            "contents": [
                {
                    "kind": "block",
                    "type": "esp32_digital_write"
                },
                {
                    "kind": "block",
                    "type": "esp32_digital_state"
                },
                {
                    "kind": "block",
                    "type": "esp32_analog_write"
                },
                {
                    "kind": "block",
                    "type": "esp32_analog_read"
                },
                {
                    "kind": "block",
                    "type": "esp32_toggle_pin"
                },
                {
                    "kind": "block",
                    "type": "esp32_interrupt"
                },
                {
                    "kind": "block",
                    "type": "esp32_detach_interrupt"
                },
                {
                    "kind": "block",
                    "type": "esp32_restart"
                },
                {
                    "kind": "block",
                    "type": "esp32_deep_sleep"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔄 Control",
            "colour": "#FFAB19",
            "contents": [
                {
                    "kind": "block",
                    "type": "controls_if"
                },
                {
                    "kind": "block",
                    "type": "ifelse"
                },
                {
                    "kind": "block",
                    "type": "ifandifnot"
                },
                {
                    "kind": "block",
                    "type": "controls_repeat_ext"
                },
                {
                    "kind": "block",
                    "type": "controls_whileUntil"
                },
                {
                    "kind": "block",
                    "type": "controls_for"
                },
                {
                    "kind": "block",
                    "type": "controls_forEach"
                },
                {
                    "kind": "block",
                    "type": "controls_switch"
                },
                {
                    "kind": "block",
                    "type": "controls_flow_statements"
                },
                {
                    "kind": "block",
                    "type": "logic_operation"
                },
                {
                    "kind": "block",
                    "type": "logic_negate"
                },
                {
                    "kind": "block",
                    "type": "logic_null"
                },
                {
                    "kind": "block",
                    "type": "inout_onoff"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔢 Operators",
            "colour": "#388E3C",
            "contents": [
                {
                    "kind": "block",
                    "type": "math_number"
                },
                {
                    "kind": "block",
                    "type": "logic_boolean"
                },
                {
                    "kind": "block",
                    "type": "math_arithmetic"
                },
                {
                    "kind": "block",
                    "type": "logic_compare"
                },
                {
                    "kind": "block",
                    "type": "math_single"
                },
                {
                    "kind": "block",
                    "type": "math_trig"
                },
                {
                    "kind": "block",
                    "type": "math_constant"
                },
                {
                    "kind": "block",
                    "type": "math_modulo"
                },
                {
                    "kind": "block",
                    "type": "math_round"
                },
                {
                    "kind": "block",
                    "type": "math_random_int"
                },
                {
                    "kind": "block",
                    "type": "math_number_property"
                },
                {
                    "kind": "block",
                    "type": "intervalle"
                },
                {
                    "kind": "block",
                    "type": "custom_text_value",
                    "fields": {
                        "TEXT": "hello"
                    }
                },
                {
                    "kind": "block",
                    "type": "text_join"
                },
                {
                    "kind": "block",
                    "type": "text_length"
                },
                {
                    "kind": "block",
                    "type": "text_isEmpty"
                },
                {
                    "kind": "block",
                    "type": "custom_math_map"
                },
                {
                    "kind": "block",
                    "type": "custom_math_random_int"
                },
                {
                    "kind": "block",
                    "type": "custom_math_constrain"
                },
                {
                    "kind": "block",
                    "type": "cast_to_byte"
                },
                {
                    "kind": "block",
                    "type": "cast_to_unsigned_int"
                },
                {
                    "kind": "block",
                    "type": "cast_to_int"
                },
                {
                    "kind": "block",
                    "type": "cast_to_float"
                }
            ]
        },
        {
            "kind": "category",
            "name": "✖️ Variables",
            "colour": "#D32F2F",
            "custom": "VARIABLE_DYNAMIC"
        },
        {
            "kind": "category",
            "name": "🔔 Communicate",
            "colour": "#1976D2",
            "contents": [
                {
                    "kind": "category",
                    "name": "i USB Serial",
                    "colour": "#0277BD",
                    "contents": [
                        {
                            "kind": "block",
                            "type": "usb_serial_init"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_available"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_read_byte"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_read_string_until"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_read_number_until"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_print_format"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_print_same_line"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_print_new_line"
                        },
                        {
                            "kind": "block",
                            "type": "usb_serial_write"
                        },
                        {
                            "kind": "block",
                            "type": "custom_text_value",
                            "fields": {
                                "TEXT": "message"
                            }
                        }
                    ]
                },
                {
                    "kind": "category",
                    "name": "Bluetooth",
                    "colour": "#01579B",
                    "contents": [
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_init"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_available"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_read_byte"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_read_string_until"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_read_number_until"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_print_format"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_print_same_line"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_print_new_line"
                        },
                        {
                            "kind": "block",
                            "type": "bluetooth_serial_write"
                        },
                        {
                            "kind": "block",
                            "type": "custom_text_value",
                            "fields": {
                                "TEXT": "message"
                            }
                        }
                    ]
                }
            ]
        }
    ];
}

function getEmmiBipedalCategories() {
    return [];
}

function getEmmiBotV2Categories() {
    return [
        {
            "kind": "category",
            "name": "👀 Eyes",
            "colour": "#CB4335",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_eyes_digital"
                }
            ]
        },
        {
            "kind": "category",
            "name": "💪 Wheels",
            "colour": "#5D4037",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_wheels_simple"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔊 Buzzer",
            "colour": "#E91E63",
            "contents": [
                {
                    "kind": "block",
                    "type": "buzzer_play_rtttl"
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_rtttl_custom"
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_note"
                },
                {
                    "kind": "block",
                    "type": "buzzer_play_tone"
                },
                {
                    "kind": "block",
                    "type": "buzzer_stop"
                }
            ]
        },
        {
            "kind": "category",
            "name": "👉 Touch",
            "colour": "#FFC107",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_touch_read"
                }
            ]
        },
        {
            "kind": "category",
            "name": "🔦 Mic",
            "colour": "#1A237E",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_mic_read"
                }
            ]
        },
        {
            "kind": "category",
            "name": "💡 Light",
            "colour": "#FFA726",
            "contents": [
                {
                    "kind": "block",
                    "type": "emmi_light_read"
                }
            ]
        }
    ];
}

function getEmmiV1Categories() {
    return [
        {
            "kind": "category",
            "name": "OLED",
            "colour": "#424242",
            "contents": [
                {
                    "kind": "block",
                    "type": "eyes-oled"
                },
                {
                    "kind": "block",
                    "type": "eyes-oled_2"
                }
            ]
        }
    ];
}

function getExplorerKitCategories() {
    return [];
}

function getToolbox(boardType = 'emmi-bot-v2') {
    let categories = [];

    categories = categories.concat(getCommonCategories());

    switch (boardType) {
        case 'emmi-bipedal':
            categories = categories.concat(getEmmiBipedalCategories());
            break;
        case 'emmi-bot-v2':
            categories = categories.concat(getEmmiBotV2Categories());
            break;
        case 'emmi-v1':
            categories = categories.concat(getEmmiV1Categories());
            break;
        case 'explorer-kit':
            categories = categories.concat(getExplorerKitCategories());
            break;
    }

    return {
        kind: "categoryToolbox",
        contents: categories
    };
}

function getAvailableBoardTypes() {
    return [
        "emmi-bipedal",
        "emmi-bot-v2",
        "emmi-v1",
        "explorer-kit"
    ];
}

let ESP32Toolbox = getToolbox('emmi-bot-v2');

function getToolboxForBoard(boardType) {
    return getToolbox(boardType);
}

/**
 * Returns a localized toolbox for the given language and board type.
 * Category names are translated using EMMITranslations when available.
 */
function getLocalizedToolbox(lang, boardType) {
    if (!boardType) {
        const sel = document.getElementById('board-select');
        boardType = (sel && sel.value) || 'emmi-bot-v2';
    }

    const translations = (typeof EMMITranslations !== 'undefined' && EMMITranslations[lang])
        ? EMMITranslations[lang]
        : (typeof EMMITranslations !== 'undefined' ? EMMITranslations['en'] : null);

    // Map English category label (no emoji) -> translation key
    const categoryKeyMap = {
        'Structure': 'STRUCTURE',
        'Timing': 'TIMING',
        'Arduino': 'ARDUINO',
        'Control': 'CONTROL',
        'Operators': 'OPERATORS',
        'Variables': 'VARIABLES',
        'Communicate': 'COMMUNICATE',
        'Eyes': 'EYES',
        'Wheels': 'WHEELS',
        'Buzzer': 'BUZZER',
        'Touch': 'TOUCH',
        'Mic': 'MIC',
        'Light': 'LIGHT',
        'OLED': 'DISPLAY',
        'Legs': 'ROBOT',
        'Servo': 'SERVO'
    };

    // Original toolbox emoji per category
    const categoryEmojis = {
        'Structure': '🔧', 'Timing': '⏱️', 'Arduino': '🎛️', 'Control': '🔄',
        'Operators': '🔢', 'Variables': '✖️', 'Communicate': '🔔',
        'Eyes': '👀', 'Wheels': '💪', 'Buzzer': '🔊', 'Touch': '👉',
        'Mic': '🔦', 'Light': '💡', 'OLED': '🖥️', 'Legs': '🦵', 'Servo': '🦾'
    };

    function translateCategoryName(name) {
        if (!translations || !name) return name;
        const parts = name.trim().split(/\s+/);
        const englishLabel = parts.slice(1).join(' ') || parts[0];
        const key = categoryKeyMap[englishLabel];
        if (!key) return name;
        const translated = translations[key];
        if (!translated) return name;
        const emoji = categoryEmojis[englishLabel] || (parts.length > 1 ? parts[0] : '');
        // Strip emoji from translated value, then re-apply original toolbox emoji
        return emoji ? emoji + ' ' + translated.replace(/^[^\s]+\s/, '') : translated;
    }

    function localizeItems(items) {
        if (!Array.isArray(items)) return items;
        return items.map(item => {
            if (!item || item.kind !== 'category') return item;
            const clone = Object.assign({}, item);
            clone.name = translateCategoryName(item.name);
            if (Array.isArray(item.contents)) clone.contents = localizeItems(item.contents);
            return clone;
        });
    }

    const base = getToolbox(boardType);
    return { kind: base.kind, contents: localizeItems(base.contents) };
}