/**
 * Explorer Kit - Arduino Code Generators
 * Auto-generated by Block Creator Tool
 */

Blockly.Arduino['explorer_kit_tapmodule'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_knock_' + dropdown_pin] = 'pinMode(' + dropdown_pin + ', INPUT);';
    var code = 'digitalRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_tilt'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_tilt_' + dropdown_pin] = 'pinMode(' + dropdown_pin + ', INPUT);';
    var code = 'digitalRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_switch_button'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    var logic = this.getFieldValue('LOGIC');
    Blockly.Arduino.setups_['setup_button_' + dropdown_pin] = 'pinMode(' + dropdown_pin + ', INPUT);';
    if(logic == 'TRUE')
        var code = '(!digitalRead(' + dropdown_pin + '))';
    else
        var code = 'digitalRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_magnetic_reed'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_reed_' + dropdown_pin] = 'pinMode(' + dropdown_pin + ', INPUT);';
    var code = 'digitalRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_magnetic_hall'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_hall_' + dropdown_pin] = 'pinMode(' + dropdown_pin + ', INPUT);';
    var code = 'digitalRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_magnetic_hall_analog'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    var status = this.getFieldValue('OUTPUT_VALUE');
    if(status == '0')
        var code = 'map(analogRead(' + dropdown_pin + '),0,4095,0,100)';
    else
        var code = 'analogRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_digital_write'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    var state = block.getFieldValue('STATE');
    Blockly.Arduino.setups_['setup_output_' + dropdown_pin] = 'pinMode(' + dropdown_pin + ', OUTPUT);';
    var code = 'digitalWrite(' + dropdown_pin + ', ' + state + ');\n';
    return code;
};

Blockly.Arduino['explorer_kit_analog_read'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    var code = 'analogRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_mic_digital'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    var pullup = block.getFieldValue('PULLUP') === 'TRUE';
    var mode = pullup ? 'INPUT_PULLUP' : 'INPUT';
    Blockly.Arduino.setups_['setup_mic_' + dropdown_pin] = 'pinMode(' + dropdown_pin + ', ' + mode + ');';
    var code = 'digitalRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_mic_analog'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    var code = 'analogRead(' + dropdown_pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Shock ---
Blockly.Arduino['explorer_kit_shock'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_shock_' + pin] = 'pinMode(' + pin + ', INPUT);';
    var code = 'digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Infrared ---
Blockly.Arduino['explorer_kit_ir_digital'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_ir_' + pin] = 'pinMode(' + pin + ', INPUT);';
    var code = '!digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_ir_sensed'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_ir_' + pin] = 'pinMode(' + pin + ', INPUT);';
    var code = 'digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_ir_analog'] = function(block) {
    var pin = block.getFieldValue('PIN');
    var output = block.getFieldValue('OUTPUT');
    var code = output === 'pct'
        ? 'map(analogRead(' + pin + '), 0, 4095, 0, 100)'
        : 'analogRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_ir_write'] = function(block) {
    var pin = block.getFieldValue('PIN');
    var state = block.getFieldValue('STATE');
    Blockly.Arduino.setups_['setup_ir_write_' + pin] = 'pinMode(' + pin + ', OUTPUT);';
    return 'digitalWrite(' + pin + ', ' + state + ');\n';
};

Blockly.Arduino['explorer_kit_flame_digital'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_flame_' + pin] = 'pinMode(' + pin + ', INPUT);';
    var code = 'digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_flame_analog'] = function(block) {
    var pin = block.getFieldValue('PIN');
    var output = block.getFieldValue('OUTPUT');
    var code = output === 'pct'
        ? 'map(analogRead(' + pin + '), 0, 4095, 0, 100)'
        : 'analogRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Relay ---
Blockly.Arduino['explorer_kit_relay'] = function(block) {
    var state = block.getFieldValue('STATE');
    Blockly.Arduino.setups_['setup_relay'] = 'pinMode(26, OUTPUT);';
    return 'digitalWrite(26, ' + state + ');\n';
};

// --- Photo interrupter ---
Blockly.Arduino['explorer_kit_photo_interrupter'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_photo_' + pin] = 'pinMode(' + pin + ', INPUT);';
    var code = '!digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Touch ---
Blockly.Arduino['explorer_kit_touch_digital'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_touch_' + pin] = 'pinMode(' + pin + ', INPUT);';
    var code = 'digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_touch_analog'] = function(block) {
    var pin = block.getFieldValue('PIN');
    var code = 'touchRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Temperature ---
Blockly.Arduino['explorer_kit_temp_digital'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_temp_' + pin] = 'pinMode(' + pin + ', INPUT);';
    var code = 'digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_temp_analog'] = function(block) {
    var pin = block.getFieldValue('PIN');
    var code = 'analogRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_temp_dht'] = function(block) {
    var num = block.getFieldValue('NUM');
    var type = block.getFieldValue('TYPE');
    var measure = block.getFieldValue('MEASURE');
    Blockly.Arduino.definitions_['include_dht'] = '#include <DHT.h>';
    Blockly.Arduino.definitions_['dht_instance_' + num] = type + ' dht' + num + '(DHT_PIN_' + num + ', ' + type + ');';
    Blockly.Arduino.setups_['setup_dht_' + num] = 'dht' + num + '.begin();';
    var field = measure === 'TEMP' ? 'readTemperature()' : 'readHumidity()';
    var code = 'dht' + num + '.' + field;
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_temp_ntc'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.definitions_['ntc_calc'] = 'float readNTC(int pin) {\n  float v = analogRead(pin) * 3.3 / 4095.0;\n  float r = (10000.0 * v) / (3.3 - v);\n  return (1.0 / (log(r / 10000.0) / 3950.0 + 1.0 / 298.15)) - 273.15;\n}';
    var code = 'readNTC(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_temp_lm35'] = function(block) {
    var pin = block.getFieldValue('PIN');
    var code = '(analogRead(' + pin + ') * 3.3 / 4095.0) * 100.0';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Heartbeat ---
Blockly.Arduino['explorer_kit_heartbeat'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_hb_' + pin] = 'pinMode(' + pin + ', INPUT);';
    var code = 'digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Joystick ---
Blockly.Arduino['explorer_kit_joystick_axis'] = function(block) {
    var pin = block.getFieldValue('PIN');
    var output = block.getFieldValue('OUTPUT');
    var code = output === 'pct'
        ? 'map(analogRead(' + pin + '), 0, 4095, 0, 100)'
        : 'analogRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_joystick_button'] = function(block) {
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_joy_btn_' + pin] = 'pinMode(' + pin + ', INPUT_PULLUP);';
    var code = '!digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Rotary Encoder ---
Blockly.Arduino['explorer_kit_encoder_init'] = function(block) {
    var num = block.getFieldValue('NUM');
    var dt = block.getFieldValue('DT');
    var clk = block.getFieldValue('CLK');
    Blockly.Arduino.definitions_['include_encoder'] = '#include <ESP32Encoder.h>';
    Blockly.Arduino.definitions_['encoder_inst_' + num] = 'ESP32Encoder encoder' + num + ';';
    Blockly.Arduino.setups_['setup_enc_' + num] = 'encoder' + num + '.attachFullQuad(' + dt + ', ' + clk + ');';
    return '';
};

Blockly.Arduino['explorer_kit_encoder_write'] = function(block) {
    var num = block.getFieldValue('NUM');
    var val = block.getFieldValue('VALUE');
    return 'encoder' + num + '.setCount(' + val + ');\n';
};

Blockly.Arduino['explorer_kit_encoder_read'] = function(block) {
    var num = block.getFieldValue('NUM');
    var code = '(int32_t)encoder' + num + '.getCount()';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

Blockly.Arduino['explorer_kit_encoder_button'] = function(block) {
    var num = block.getFieldValue('NUM');
    var pin = block.getFieldValue('PIN');
    Blockly.Arduino.setups_['setup_enc_btn_' + num] = 'pinMode(' + pin + ', INPUT_PULLUP);';
    var code = '!digitalRead(' + pin + ')';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};

// --- Other ---
Blockly.Arduino['explorer_kit_mrtnode_button'] = function(block) {
    Blockly.Arduino.setups_['setup_mrtnode_btn'] = 'pinMode(0, INPUT_PULLUP);';
    var code = '!digitalRead(0)';
    return [code, Blockly.Arduino.ORDER_ATOMIC];
};


