/**
 * Explorer Kit - Python Code Generators
 * Auto-generated by Block Creator Tool
 */

Blockly.Python['explorer_kit_tapmodule'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    return ['# tapmodule on pin ' + dropdown_pin + '\npass', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_tilt'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    return ['# tilt on pin ' + dropdown_pin + '\npass', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_switch_button'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    return ['# button on pin ' + dropdown_pin + '\npass', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_magnetic_reed'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    return ['# reed switch on pin ' + dropdown_pin + '\npass', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_magnetic_hall'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    return ['# hall magnetic on pin ' + dropdown_pin + '\npass', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_magnetic_hall_analog'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
};

Blockly.Python['explorer_kit_digital_write'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    var state = block.getFieldValue('STATE');
    return '# digital write ' + dropdown_pin + ' to ' + state + '\npass\n';
};

Blockly.Python['explorer_kit_analog_read'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    return ['# analog read ' + dropdown_pin + '\npass', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_mic_digital'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    return ['# digital read mic ' + dropdown_pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_mic_analog'] = function(block) {
    var dropdown_pin = block.getFieldValue('PIN');
    return ['# analog read mic ' + dropdown_pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_shock'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# shock on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_ir_digital'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# IR08H on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_ir_sensed'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# infrared sensed on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_ir_analog'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# infrared analog on pin ' + pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_ir_write'] = function(block) {
    var pin = block.getFieldValue('PIN');
    var state = block.getFieldValue('STATE');
    return '# digital write infrared ' + pin + ' to ' + state + '\npass\n';
};

Blockly.Python['explorer_kit_flame_digital'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# flame digital on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_flame_analog'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# flame analog on pin ' + pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_relay'] = function(block) {
    var state = block.getFieldValue('STATE');
    return '# relay switch ' + state + '\npass\n';
};

Blockly.Python['explorer_kit_photo_interrupter'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# photo interrupter on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_touch_digital'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# touch digital on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_touch_analog'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# touch analog on pin ' + pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_temp_digital'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# digital temp on pin ' + pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_temp_analog'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# analog temp on pin ' + pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_temp_dht'] = function(block) {
    return ['# DHT temperature/humidity\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_temp_ntc'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# NTC temp on pin ' + pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_temp_lm35'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# LM35 temp on pin ' + pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_heartbeat'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# heartbeat on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

// --- Joystick ---
Blockly.Python['explorer_kit_joystick_axis'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# joystick axis on pin ' + pin + '\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_joystick_button'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# joystick btn on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

// --- Rotary Encoder ---
Blockly.Python['explorer_kit_encoder_init'] = function(block) {
    return '# encoder init\npass\n';
};

Blockly.Python['explorer_kit_encoder_write'] = function(block) {
    var val = block.getFieldValue('VALUE');
    return '# encoder write ' + val + '\npass\n';
};

Blockly.Python['explorer_kit_encoder_read'] = function(block) {
    return ['# encoder read\n0', Blockly.Python.ORDER_ATOMIC];
};

Blockly.Python['explorer_kit_encoder_button'] = function(block) {
    var pin = block.getFieldValue('PIN');
    return ['# encoder btn on pin ' + pin + '\nFalse', Blockly.Python.ORDER_ATOMIC];
};

// --- Other ---
Blockly.Python['explorer_kit_mrtnode_button'] = function(block) {
    return ['# MRTNode start button\nFalse', Blockly.Python.ORDER_ATOMIC];
};
